#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Parameters --------------------------------
skip_files=false
skip_theme=false

while [ ! -z "$1" ]; do
  case "$1" in
     --skip-files|-sf)
         shift
         skip_files=true
         ;;
     --skip-theme|-st)
         shift
         skip_theme=true
         ;;
  esac
done

#-------------------------- Execution --------------------------------

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
fin project reset -f

# Site initialization
echo -e "${green_bg} Step 2 ${NC}${green} Initializing local settings...${NC}"
fin init-site

# Import the database
echo -e "${green_bg} Step 3 ${NC}${green} Importing the database...${NC}"
fin pull db -y

# Rsync the files
echo -e "${green_bg} Step 4 ${NC}${green} Rsyncing the files...${NC}"
files_directory=$(fin drush drupal-directory files | tr -d '\r')

if [ "$skip_files" = false ] ; then
    fin pull files -y
else
  echo 'Creating the files directory...'
  fin exec [ -d ${files_directory} ] || fin exec mkdir ${files_directory}
fi

fin exec chmod -R +rwX ${files_directory}

# Apply the database updates
echo -e "${green_bg} Step 5 ${NC}${green} Applying the database updates...${NC}"
fin drush updb -y

# Import the configuration
echo -e "${green_bg} Step 6 ${NC}${green} Importing the site configuration...${NC}"
fin drush cim -y

# Sanitize the database
echo -e "${green_bg} Step 7 ${NC}${green} Sanitizing the database...${NC}"
fin drush sqlsan -y
fin drush user:password "admin" "password"

# Build them theme.
echo -e "${green_bg} Step 8 ${NC}${green} Build the theme...${NC}"

if [ "$skip_theme" = false ] ; then
    fin npm-install
    fin build-theme
else
    echo 'Skipping...'
fi

echo -e "${green_bg} DONE! ${NC}${green} Completed all initialization steps.${NC}"
echo 'Clearing the cache...'
fin drush cr
fin drush uli

#-------------------------- END: Execution --------------------------------
